openapi: "3.0.0"
info:
  version: 1.0.0-$REVISION
  title: OpenAPI Definition for Simple Commerce - Users service
  license:
    name: MIT
servers:
  - url: https://arieffian.com/api/v1
    description: development server
paths:
  # Users
  /get-users/{page}:
    $ref: "./paths/get_users.yml"
  /get-user-by-id/{id}:
    $ref: "./paths/get_user_by_id.yml"
  /create-user:
    $ref: "./paths/create_new_user.yml"
  /update-user-by-id/{id}:
    $ref: "./paths/update_user_by_id.yml"
  /delete-user-by-id/{id}:
    $ref: "./paths/delete_user_by_id.yml"

components:
  schemas:
    $ref: "./schemas/_main.yml"
  responses:
    $ref: "./responses/_main.yml"
  parameters:
    $ref: "./parameters/_main.yml"
  securitySchemes:
    $ref: "./security-schemes/_main.yml"
security:
  - ApiKeyAuth: []
  - BearerAuth: []
